"""
Archive — CAM-based localisation (replaced by HSV approach).

This was the original localize_and_draw() implementation. It used Class Activation
Maps generated by HotspotCAM to find the hotspot location.

Why it was replaced:
  At 24×32, each CAM cell covers a 4×4 pixel block. Upscaling a 6×8 heatmap to the
  full image size means the highlighted region covers a large fraction of the image —
  not precise enough to draw a meaningful circle around a specific anomaly.

  HSV thresholding reads location directly from the false-colour image (warm pixels
  are orange/yellow) and gives pixel-accurate results without needing the model at all
  for the localisation step.

Kept here as a reference for:
  - Understanding why CAM alone is insufficient at this resolution
  - Future use if the camera is upgraded to higher resolution (e.g. 160×120),
    at which point CAM cells would be small enough to localise precisely
"""

import os
import cv2
import numpy as np


def localize_and_draw_cam(image_path, classifier, transform, device,
                          hotspot_idx, cam_threshold, output_dir="flagged_images"):
    """
    Localise hotspot using Class Activation Maps and save annotated image.

    Args:
        image_path:    path to thermal PNG
        classifier:    loaded HotspotCAM model (eval mode)
        transform:     inference transform used during classification
        device:        torch device
        hotspot_idx:   class index for 'hotspot' in the model's output
        cam_threshold: fraction of max CAM activation to threshold at (e.g. 0.5)
        output_dir:    directory to save annotated image

    Returns:
        (save_path, cx, cy) — path to annotated image and centre of largest contour
    """
    from PIL import Image
    import torch

    os.makedirs(output_dir, exist_ok=True)

    img_tensor = transform(Image.open(image_path).convert("RGB")).unsqueeze(0).to(device)
    cam_raw    = classifier.generate_cam(img_tensor, hotspot_idx)

    img_cv       = cv2.imread(image_path)
    img_h, img_w = img_cv.shape[:2]

    cam_up    = np.clip(cv2.resize(cam_raw, (img_w, img_h), interpolation=cv2.INTER_CUBIC), 0, 1)
    cam_uint8 = (cam_up * 255).astype(np.uint8)
    _, binary = cv2.threshold(cam_uint8, int(cam_threshold * 255), 255, cv2.THRESH_BINARY)

    contours, _ = cv2.findContours(binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    cx, cy = img_w // 2, img_h // 2
    if contours:
        largest      = max(contours, key=cv2.contourArea)
        (cx, cy), r  = cv2.minEnclosingCircle(largest)
        cx, cy       = int(cx), int(cy)
        cv2.circle(img_cv, (cx, cy), max(int(r) + 2, 3), (0, 0, 255), 1)
        cv2.circle(img_cv, (cx, cy), 1, (0, 0, 255), -1)

    save_path = os.path.join(output_dir, f"LOCATED_{os.path.basename(image_path)}")
    cv2.imwrite(save_path, img_cv)
    return save_path, cx, cy
